
name: CICD

on:
  push:
    branches: [master]

jobs:
  build:
    runs-on: [ubuntu-latest]
    steps:
      - name: Checkout source
        uses: actions/checkout@v4
 
      - name: Login to docker hub
        run:  docker login -u ${{ secrets.DOCKER_USERNAME }} -p dckr_pat_ICLqRUbjZevWm4bWAmj7fpm7MzE
      - name: Build docker image
        run: docker build -t adlane95/websocket-server:latest .
      - name: Publish image to docker hub
        run: docker push adlane95/websocket-server:latest
        
  deploy:
    needs: build
    runs-on: self-hosted   
    steps:  
      - name: Login to docker hub
        run: sudo docker login -u ${{ secrets.DOCKER_USERNAME }} -p dckr_pat_ICLqRUbjZevWm4bWAmj7fpm7MzE

      - name: Pull image from docker hub
        run: sudo docker pull adlane95/websocket-server:latest
      - name: Delete old container
        run: sudo docker rm -f websocket-server-container
      - name: Run docker container
        run: sudo docker run -d -p 3000:3000 --name websocket-server-container adlane95/websocket-server
